language: cpp

cache: ccache

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

# The following gives us Ubuntu 14.04 LTS instead of 12.04 LTS
sudo: required
dist: trusty

install:
    - if test "$TRAVIS_OS_NAME" = "osx" -a "$CXX" = "g++"; then
        brew update &&
        brew install gcc6 &&
        export CXX=g++-6 CC=gcc-6;
      fi
    - if test "$TRAVIS_OS_NAME" = "osx" -a "$CXX" = "clang++"; then
        brew update &&
        brew install llvm &&
        export CXX=/usr/local/opt/llvm/bin/clang++ CC=/usr/local/opt/llvm/bin/clang &&
        export LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib" &&
        export CPPFLAGS=-I/usr/local/opt/llvm/include
      fi
    - if test "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++"; then
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y &&
        sudo apt-get update -q &&
        sudo apt-get install g++-6 -y &&
        export CXX=g++-6 CC=gcc-6;
      fi
    - if test "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "clang++"; then
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y &&
        sudo apt-get update -q &&
        sudo apt-get install clang-3.8 libstdc++-6-dev &&
        export CXX=clang++-3.8 CC=clang-3.8;
      fi

before_script:
    - $CXX --version
    - cmake --version
    - export dashboard_model=Experimental
    - export build_type=Release
    - export NUMBER_OF_PROCESSORS=2

script:
    - ctest -V -S test.cmake

notifications:
    email: false
    irc:
        channels:
            - "chat.freenode.net##Vc"
        on_success: change # [always|never|change] # default: always
        on_failure: always # [always|never|change] # default: always
        use_notice: true
        skip_join: true
